replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/mle-course-454508/mlops-repo/phone-price-api-fastapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow-mlflow:5000"

