apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fastapi  # label giống với service FastAPI
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s

