{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fastapi.fullname" . }}-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.service.selectorLabels | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
{{- end }}

