replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/mle-course-454508/mlops-repo/phone-price-api-mlflow
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

