apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app: {{ include "mlflow.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mlflow.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mlflow.name" . }}
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          command: ["mlflow", "server"]
          args:
            {{- range .Values.args }}
            - "{{ . }}"
            {{- end }}
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow_app
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-pvc
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}

